"""initial migration

Revision ID: 4986439a9420
Revises: 
Create Date: 2025-10-25 10:00:37.443425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4986439a9420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo', sa.String(length=200), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_brand', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('falla', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('required_parts', sa.Text(), nullable=True),
    sa.Column('repair_cost', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('valoraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoraciones')
    op.drop_table('ordenes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
